
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA HOLA QUE TAL\n\tS : HOLA X\n\t\t| HOLA Y\n\t\t| HOLA\n\t\n\tX : COMA S\n\t\t|\n\t\n\tY : QUE TAL\n\t'
    
_lr_action_items = {'HOLA':([0,5,],[2,2,]),'$end':([1,2,3,4,7,8,],[0,-3,-1,-2,-4,-6,]),'COMA':([2,],[5,]),'QUE':([2,],[6,]),'TAL':([6,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,5,],[1,7,]),'X':([2,],[3,]),'Y':([2,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> HOLA X','S',2,'p_S','AnalizadorLexico.py',46),
  ('S -> HOLA Y','S',2,'p_S','AnalizadorLexico.py',47),
  ('S -> HOLA','S',1,'p_S','AnalizadorLexico.py',48),
  ('X -> COMA S','X',2,'p_X','AnalizadorLexico.py',54),
  ('X -> <empty>','X',0,'p_X','AnalizadorLexico.py',55),
  ('Y -> QUE TAL','Y',2,'p_Y','AnalizadorLexico.py',60),
]
